# Generated by Django 4.2.20 on 2025-05-06 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsOfServiceVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(
                        help_text="e.g., '1.0', '2024-07-15'",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The full text of the Terms of Service for this version."
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this version becomes active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Terms of Service Version",
                "verbose_name_plural": "Terms of Service Versions",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tos_accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the user accepted the ToS.",
                        null=True,
                    ),
                ),
                (
                    "accepted_tos_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific version of ToS accepted by the user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_by_profiles",
                        to="core.termsofserviceversion",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
