# Generated by Django 4.2.20 on 2025-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0002_migrate_ingredient_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="unit",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fdc_id",
            field=models.IntegerField(default=999, unique=True),
            preserve_default=False,
        ),
    ]
