# Generated by Django 4.2.20 on 2025-04-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0003_modify_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="priority",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
