# Generated by Django 4.2.20 on 2025-04-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groceries", "0001_refactor_folder_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedrecipe",
            name="grocery_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plannedrecipes",
                to="groceries.grocerylist",
            ),
        ),
    ]
