# Generated by Django 4.2.20 on 2025-04-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0004_ingredient_priority"),
        ("groceries", "0002_alter_plannedrecipe_grocery_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="grocerylistitem",
            name="unit",
            field=models.ForeignKey(
                default=99,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grocerylistitems",
                to="ingredients.ingredientunit",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plannedextra",
            name="unit",
            field=models.ForeignKey(
                default=99,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plannedextras",
                to="ingredients.ingredientunit",
            ),
            preserve_default=False,
        ),
    ]
