# Generated by Django 4.1.4 on 2023-06-18 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0004_grocerylist_created_at_grocerylist_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grocerylist",
            options={"get_latest_by": "timestamp"},
        ),
        migrations.AlterField(
            model_name="grocerylist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
