# Generated by Django 4.1.4 on 2023-06-18 20:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0005_alter_grocerylist_options_alter_grocerylist_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GroceryList",
            new_name="GroceryListItem",
        ),
    ]
