# Generated by Django 4.1.4 on 2024-10-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_add_new_link_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.FloatField()),
                (
                    "grocery_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plannedextras",
                        to="recipes.grocerylist",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plannedextras",
                        to="recipes.ingredient",
                    ),
                ),
            ],
        ),
    ]
