# Generated by Django 4.2.20 on 2025-04-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_add_feed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeditem",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_recipe", "New Recipe"),
                    ("new_rating", "New Rating"),
                    ("update_recipe", "Update Recipe"),
                    ("update_rating", "Update Rating"),
                ],
                max_length=20,
            ),
        ),
    ]
