# Generated by Django 4.1.4 on 2023-06-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_remove_grocerylistitem_user_grocerylist_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GroceryListItem",
            new_name="PlannedRecipe",
        ),
    ]
