# Generated by Django 4.1.4 on 2023-06-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_rename_grocery_list_item_to_planned_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(default="gr", max_length=50),
            preserve_default=False,
        ),
    ]
