# Generated by Django 4.2.20 on 2025-04-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_add_planned_extras"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedrecipe",
            name="planned_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
