# Generated by Django 4.2.20 on 2025-04-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_add_planned_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedextra",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plannedextras",
                to="recipes.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recipes.ingredient"
            ),
        ),
        migrations.CreateModel(
            name="GroceryListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_recipes", models.TextField()),
                ("quantity", models.FloatField()),
                ("is_checked", models.BooleanField(default=False)),
                (
                    "grocery_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grocerylistitems",
                        to="recipes.grocerylist",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grocerylistitems",
                        to="recipes.ingredient",
                    ),
                ),
            ],
        ),
    ]
