# Generated by Django 4.2.20 on 2025-04-18 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_refactor_folder_structure"),
        ("recipes", "0013_add_grocery_list_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grocerylistitem",
            name="grocery_list",
        ),
        migrations.RemoveField(
            model_name="grocerylistitem",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="plannedextra",
            name="grocery_list",
        ),
        migrations.RemoveField(
            model_name="plannedextra",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="plannedrecipe",
            name="grocery_list",
        ),
        migrations.RemoveField(
            model_name="plannedrecipe",
            name="recipe",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipes.RecipeIngredient",
                to="ingredients.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ingredients.ingredient"
            ),
        ),
        migrations.DeleteModel(
            name="GroceryList",
        ),
        migrations.DeleteModel(
            name="GroceryListItem",
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.DeleteModel(
            name="PlannedExtra",
        ),
        migrations.DeleteModel(
            name="PlannedRecipe",
        ),
    ]
