# Generated by Django 4.2.20 on 2025-04-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0003_modify_ingredients"),
        ("recipes", "0015_add_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="unit",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.PROTECT,
                to="ingredients.ingredientunit",
            ),
            preserve_default=False,
        ),
    ]
